### ISSUE TITLE
Sorting the plot from chromeister

### ISSUE THREAD

**Issue by harmeet1990** [estebanpw/chromeister#13]
Hi 
Is it possible to sort the chromeister plot according to the reference coordinates? I found a thread discussing the same using Mauve but I am dealing with a huge genome and It doesn't work.

Thanks

**Comment by estebanpw** [comment]
Hello @harmeet1990 

CHROMEISTER just compares the query and reference sequences in the given order in the FASTA file. 

So I think you would need to reorder the sequences in the reference FASTA file before running the comparison. How do the reference coordinates look like? And how long is each sequence in the reference? (aprox). 
It maybe can be done with some linux sort pipeline.

**Comment by harmeet1990** [comment]
Ya I can sort the fasta but I was hoping for simpler where the Rscript for plotting also sorts the files. I am dealing with bread wheat and each sequence is between 400 to 800 Mb.

**Comment by estebanpw** [comment]
Unfortunately it cant do that (yet), and I gues you will have to manually sort the files. But its an interesting feature. We will consider including this for a further release!

Bests
