### ISSUE TITLE
compute_score.r error

### ISSUE THREAD

**Issue by manishbiotechie** [estebanpw/chromeister#14]
I installed the chromeister using conda.

I run the command
CHROMEISTER -query GENOME1.fasta -db GENOME2.fasta -out dotplot.mat -dimension 2000 && Rscript compute_score.R dotplot.mat 2000
but at last I faced issue of 
Fatal error: cannot open file 'compute_score.R': No such file or directory

I will be thankful for help.

**Comment by estebanpw** [comment]
Hello @manishbiotechie 

This error is known and has been fixed; however it is not yet available in bioconda. Please download it from this github and follow the instructions to compile it, or wait a few days and I will let you know when the bioconda repository is updated.

Sorry for the inconvenience!

**Comment by estebanpw** [comment]
Hello @manishbiotechie 
the update is already on bioconda now. Please try again and let me know if it is all working. 
Best regards,
Esteban
