### ISSUE TITLE
Breakpoint about inversion

### ISSUE THREAD

**Issue by Chenglin20170390** [estebanpw/chromeister#26]
Hello Esteban,

    Many thanks for developing such useful tools.
   
    1). I would like to use  chromeister to check inversion and their breakpoint (first figure).  Does chromeister can highlight or report the breakpoint of inversion in the png? 
    2). When I use chromeister to check the small inversion event, I find the figure not like dotpoint(second figure), but dotline. it's because of  k-mer size?  

     Thanks.
<img width="745" alt="inv breakpoint" src="https://user-images.githubusercontent.com/33062118/173297064-9a43aef4-27c4-482f-93a4-5b490f55c809.png">

<img width="718" alt="image" src="https://user-images.githubusercontent.com/33062118/173301706-3e8ade0d-37d5-4e43-910c-61717c64bdda.png">

best,
Lin

**Comment by estebanpw** [comment]
Hello Lin!
thanks for your feedback :) 

Regarding 1) if I understand correctly you want to have the coordinates of the inversions? There is approximate support for that (see [here](https://github.com/estebanpw/chromeister#events-detection) and also more details and a tutorial [here](https://training.galaxyproject.org/training-material/topics/genome-annotation/tutorials/hpc-for-lsgc/tutorial.html#post-processing-detecting-rearrangements). Note that by approximate I mean that CHROMEISTER loses a lot of precision while scaling down the comparison, so the breakpoint's coordinates will be approximate in plus/minus several thousand base pairs. If this is not good enough, I suggest you use GECKO for the particular region.

Regarding 2) I think this is a problem related to the visualization given the size of the sequences. CHROMEISTER is aimed at comparing chromosomes (although it also works for small ~1MB sequences). According to the coordinates in the plot, the sequences appear to be around 3,000 base pairs. In that case I recommend to run GECKO or BLAST. In fact, you can find information on how to do this on the Galaxy workflow manager [here](https://training.galaxyproject.org/training-material/topics/genome-annotation/tutorials/hpc-for-lsgc/tutorial.html#post-processing-extracting-alignments) for free and without requiring command line.

Also, please note that at the moment I am unable to dedicate much time to this repo but if needed I will take a closer look during the weekend. Let me know if this helps!

Bests,
Esteban

**Comment by Chenglin20170390** [comment]
Thanks, I will try it.
