### ISSUE TITLE
error  cannot open file 'dotplot.mat.csv': No such file or directory

### ISSUE THREAD

**Issue by XuewenWangUGA** [estebanpw/chromeister#3]
$scriptdir/CHROMEISTER -query aradu.K30065.gnm1.chr01.fa -db aradu.K30060.gnm1.chr01.fa -out dotplot.mat -dimension 2000 

output: 7.7M
dotplot.mat

error: 
$ Rscript $scriptdir/compute_score.R dotplot.mat 2000
Error in file(con, "r") : cannot open the connection
Calls: unlist -> readLines -> file
In addition: Warning message:
In file(con, "r") :
  cannot open file 'dotplot.mat.csv': No such file or directory
Execution halted

##it seems that the output "dotplot.mat.csv " is missing

**Comment by estebanpw** [comment]
Thanks for reporting this. The grid update introduced an error which was only apparent if the -dimension parameter was used. It should be now fixed. 

Please update your repository using "git pull origin", then compile the files again with "make all" within the /src folder and rerun your experiment.

As a sidenote, also remember that if your input FASTA sequence is a multifasta containing more than ~50 sequences, then you should used the alternative script:

`Rscript $scriptdir/compute_score-nogrid.R dotplot.mat 2000`

**Comment by XuewenWangUGA** [comment]
Thank you for your updating and fixing the issue.
I have downloaded the bin and run a test. It still has the same type of issue.

My testing data has only one seq in each input file. One sequence is around 100 Mbp and the other is around 95Mbp. I tested the tool on Ubuntu 18.04.
It seems that the .csv output file is missing.
my scripts:
scriptdir=/home/xuewen/Downloads/chromeister-master/bin
$scriptdir/CHROMEISTER -query aradu.K30065.gnm1.chr01.fa -db aradu.K30060.gnm1.chr01.fa -out dotplot.mat -dimension 2000 && Rscript $scriptdir/compute_score.R dotplot.mat 2000

Do you have any suggestions on this?
Thanks.

Xuewen






Xuewen

________________________________

**Comment by XuewenWangUGA** [comment]
The dotplot.mat file is generated but file "dotplot.mat.csv" is missing.

Here is the error information:

Error in file(con, "r") : cannot open the connection
Calls: unlist -> readLines -> file
In addition: Warning message:
In file(con, "r") :
  cannot open file 'dotplot.mat.csv': No such file or directory
Execution halted



Xuewen

________________________________

**Comment by XuewenWangUGA** [comment]
scriptdir=/home/xuewen/Downloads/chromeister-master/bin
$scriptdir/CHROMEISTER -query aradu.K30065.gnm1.chr01.fa -db aradu.K30060.gnm1.chr01.fa -out dotplot.mat -dimension 2000 && Rscript $scriptdir/compute_score.R dotplot.mat 2000

more detailed log from above command:

[INFO] Loading database
[INFO] Database loaded and of length 93964718. Hash table building took 1.422648e+01 seconds
[INFO] Generating hits
[INFO] Ratios: Q [5.574391e+04] D [4.698236e+04]. Lenghts: Q [111487820] D [93964718]
11%..21%..31%..41%..51%..61%..71%..81%..91%..
[INFO] Query length 110111402. Hits completed. Took 2.596973e+03 seconds
[INFO] Writing matrix
Error in file(con, "r") : cannot open the connection
Calls: unlist -> readLines -> file
In addition: Warning message:
In file(con, "r") :
  cannot open file 'dotplot.mat.csv': No such file or directory
Execution halted



Xuewen Wang, PhD

University of Georgia

email: xwwang@uga.edu

________________________________

**Comment by XuewenWangUGA** [comment]
Esteban,

Finally I made it work. Thanks.
I downloaded and recompiled the src.



Xuewen Wang, PhD

University of Georgia

email: xwwang@uga.edu

________________________________

**Comment by XuewenWangUGA** [comment]
Estebapw,

I have one question for you on how to understand the coordinate file "master.csv"
Is the xStart, yStart the position (bp) in the sequence or the position in the plot?

Here is the first several lines of "master.csv"

Type,xStart,yStart,xEnd,yEnd,strand(f/r),block,length,score,ident,similarity,%ident,SeqX,SeqY
Frag,121889,350742,122027,350880,f,0,139,500,132,89.93,0.95,0,0
Frag,322460,528543,322600,528683,f,0,141,468,129,82.98,0.91,0,0
Frag,326298,532332,327156,533190,f,0,859,2772,776,80.68,0.90,0,0
Frag,4431,109033,4638,109240,f,0,208,704,192,84.62,0.92,0,0
Frag,311,104565,538,104792,f,0,228,768,210,84.21,0.92,0,0

Thanks.


Xuewen Wang, PhD

University of Georgia

email: xwwang@uga.edu

________________________________

**Comment by estebanpw** [comment]
My bad, I updated the repository but forgot to update the release package :-)

First, I assume you were able to generate the .png file of the dotplot and then proceeded to run GECKO with the guide_fastas script to generate the alignments.

**NOTE:** please update your whole chromeister and gecko repository (I have just pushed an update that improves precision in the alignments from GECKO) and the re-run your experiment completely.


Regarding your question, those coordinates are in the sequence. 
Also, if you are interested in obtaining the alignments (as text, such as in blast) you can do now by running the "guided_fastas.sh" script with a 1 at the end, in this fashion:

`bin/guidefastas.sh X.fasta Y.fasta hits-XY-dotplot.mat.hits 1000 100 60 32 1`

The one at the end indicates you want the alignments --beware, if there are many long alignments it will take some time. You can disable this option by running it with a 0 at the end.

Additionally you can visualize the master.csv file here:
https://pistacho.ac.uma.es/

Just upload it by using the "Load frags from local" button. 

Btw, may I ask the size of your sequences? 

Best regards,
Esteban

**Comment by XuewenWangUGA** [comment]
Thanks a lot. It is very helpful.


Xuewen

________________________________

**Comment by XuewenWangUGA** [comment]
In addition, there is another small issue where the removal of "index-refseq-qryseq.csv" is not successful, which cause an error.
It seems that that is caused by the directory /path issue.

I already put this information on github so you can fix it.



Xuewen

________________________________

**Comment by XuewenWangUGA** [comment]
Estebanpw,

I have one suggestion. Since the alignment is based on similarity, is that possible to color the dotplot with the similarity score in your scripts?


Xuewen

________________________________

**Comment by estebanpw** [comment]
In the case of the .png dotplot, no, thats not possible due to how chromeister works.
However, what you could do is take the .csv that is output by GECKO after using the guide_fastas script, upload here https://pistacho.ac.uma.es/ and then filter by similarity. This will remove alignments that do not meet the similarity threshold. See an example:

![imagen](https://user-images.githubusercontent.com/4108045/83289506-71613480-a1e5-11ea-9773-9a06bf1d7dad.png)

Best regards,
Esteban
