### ISSUE TITLE
Whole genome comparisons.

### ISSUE THREAD

**Issue by sahirmohit** [estebanpw/chromeister#5]
Hi.
Can chromeister  be used for comparing whole genome of two mammals such as human and chimp.
if we need to specify/modify  certain parameters please mention those as well..

thank you.

mohit

**Comment by estebanpw** [comment]
Dear mohit,

yes, it can be used. In fact it was done for the original publication (see here https://www.nature.com/articles/s41598-019-46773-w).

If you are comparing each chromosome against each other, leave the parameters default.
If you are comparing the two genomes at once (i.e. in only one comparison with every chromosome concatenated in a single fasta file) then you should use the parameter -dimension 2000 and also specify this in the plot script, e.g.:

./CHROMEISTER -query GENOME1.fasta -db GENOME2.fasta -out dotplot.mat -dimension 2000 && Rscript compute_score.R dotplot.mat 2000

That is, if you are comparing two fasta files of size over 300 MB you should use -dimension 2000 to get a better dotplot.

Hope it helps,
Esteban
